### ISSUE TITLE
No table names shown on PHP 7.3 

### ISSUE THREAD

**Issue by levelsio** [phpLiteAdmin/pla#14]
<img width="948" alt="screen shot 2018-12-07 at 6 36 21 pm" src="https://user-images.githubusercontent.com/7150848/49639745-1bc42580-fa4f-11e8-9c06-74190f383c0d.png">

We just upgraded to PHP 7.3 and phpLiteAdmin 1.9.7 doesn't show table names anymore.

**Comment by levelsio** [comment]
@neosilky

**Comment by crazy4chrissi** [comment]
Thanks for reporting. I currently don't have a PHP 7.3 here. Could you please turn on debug mode (`$debug=true` in the config) and post any error messages shown?`

And you can also have a try with the devlopment version http://www.phpliteadmin.org/phpliteadmin-dev.zip - maybe it is already fixed there

**Comment by levelsio** [comment]
> Thanks for reporting. I currently don't have a PHP 7.3 here. Could you please turn on debug mode (`$debug=true` in the config) and post any error messages shown?`
> 
> And you can also have a try with the devlopment version http://www.phpliteadmin.org/phpliteadmin-dev.zip - maybe it is already fixed there

Here you go:

<img width="948" alt="screen shot 2018-12-07 at 6 52 46 pm" src="https://user-images.githubusercontent.com/7150848/49640580-5038e100-fa51-11e8-9f9a-85b1213e90ba.png">

**Comment by crazy4chrissi** [comment]
Thank you. I just tried to reproduce this, but could not so far:
![grafik](https://user-images.githubusercontent.com/6806325/49642010-2ca27600-fa12-11e8-86d2-becfd4c4d761.png)

This is a PHP 7.3.0 on Windows with the built-in webserver running phpLiteAdmin 1.9.7.1 without problem.

Instead, I found another error that occurs in PHP 7.3 when creating a new database. I just fixed that in the development version.

I guess I will set up an Ubuntu 18.04 with the PHP 7.3 from deb.sury.org to get a similar environement as you have.

Can you please tell me what this PHP outputs for you?
`<?php var_dump(ENT_QUOTES); ?>`

**Comment by daniellockyer** [comment]
Hi @crazy4chrissi, sorry for the late reply.

I think it's actually a PHP 7.3 issue. I can't be 100% here but we've also been experiencing a ton of other issues and reverted back to 7.2 for now. I'm sure you can replicate if you install the same version from deb.sury.org. Their bug tracker also lists a ton of issues re: Opcache.

Thanks for looking into it and we'll see if future updates fix it.

**Comment by crazy4chrissi** [comment]
I close this as in https://github.com/phpLiteAdmin/pla/issues/19 it was reported, that the phpLiteAdmin development version which just became 1.9.8.2 is compatible with PHP 7.3.9.

The error messages reported in this issue look like the constant `ENT_QUOTES` is not defined, which should not be the case in PHP 7.3. So I think the PHP version used here was somehow faulty, as also indicated by @daniellockyer .
