### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by halojoy** [phpLiteAdmin/pla#16]
1.9.7.1 is very old.
I think it is really time for an updated release.

I use PHP 7.3 and there are several issues with phpliteadmin-1.9.7.1.
We should appreciate an updated release with the latest developments changes.

**Comment by crazy4chrissi** [comment]
Yes, very true.
Development branch has so many improvements over 1.9.7.1.
Of course it is always available here: https://www.phpliteadmin.org/phpliteadmin-dev.zip
But sure, we need to make it stable.
I will try to do it soon, maybe even today.

**Comment by crazy4chrissi** [comment]
Version 1.9.8 finally released today.
