### ISSUE TITLE
login failed on on PHP 7.3.9

### ISSUE THREAD

**Issue by dehim** [phpLiteAdmin/pla#19]
vi classes/Authorization.php

find "self::generateSalt(20)"  ->   "self::generateSalt(22)" 

and it works.

**Comment by crazy4chrissi** [comment]
Can you explain why this is necessary?

**Comment by crazy4chrissi** [comment]
Ok, this is Blowfish so the salt for `crypt` should be 22 characters. Strange why it even worked before.

**Comment by crazy4chrissi** [comment]
Can you please check whether the current development version works?

https://www.phpliteadmin.org/phpliteadmin-dev.zip

**Comment by dehim** [comment]
> Can you please check whether the current development version works?
> 
> https://www.phpliteadmin.org/phpliteadmin-dev.zip

OK，it runs perfectly

**Comment by crazy4chrissi** [comment]
Fixed with phpLiteAdmin 1.9.8.2 released just now.
