### ISSUE TITLE
Update the theme pack in website.

### ISSUE THREAD

**Issue by NaveenDA** [phpLiteAdmin/pla#21]
In website, the theme pack not updated more than 3.5 years. Please update the theme pack.

![Screenshot 18_09_2019 at 01_07 PM](https://user-images.githubusercontent.com/20555082/65127647-83af8f80-da15-11e9-811d-a276342f7c6f.png)

**Comment by crazy4chrissi** [comment]
Thanks for opening the issue. I just updated the themes pack.
