### ISSUE TITLE
Error in PHP 7.1.0 when scan subdirectories.

### ISSUE THREAD

**Issue by halojoy** [phpLiteAdmin/pla#5]
Line number 217, in trunk index.php 
$path[] = $thisdir.DIRECTORY_SEPARATOR.$dircont[$i];
gives
"Error: [] operator not supported for strings"

This error happens when settting scan subdirectories TRUE.

**Comment by crazy4chrissi** [comment]
Can you confirm this error is gone with the just commited fix?

**Comment by halojoy** [comment]
You are fantastic!
It works well now in PHP 7.1.0.
Now I can scan directories.
